services:
  eshop.api:
    image: eshop.api
    build:
      context: .
      dockerfile: src/backend/EShop.Api/Dockerfile

  eshop.emailworker:
    image: eshop.emailworker
    build:
      context: .
      dockerfile: src/backend/Workers/EShop.EmailWorker/Dockerfile

