<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-EShop.EmailWorker-88c6ac05-c407-44fe-9da5-52cb0959f2fe</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Email/Templates/Register.html"/>
        <EmbeddedResource Include="Email/Templates/Reset.html"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" />
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="WolverineFx.RabbitMQ" />
        <PackageReference Include="WolverineFx"/>
        <PackageReference Include="WolverineFx.RuntimeCompilation"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\EShop.Contracts\EShop.Contracts.csproj" />
    </ItemGroup>
</Project>
